---
pipeline:
  projectIdentifier: "DoNotDelete_Mayank"
  orgIdentifier: "Ng_Pipelines_K8s_Organisations"
  tags: {}
  stages:
  - stage:
      name: "te"
      identifier: "te"
      description: ""
      type: "Custom"
      spec:
        execution:
          steps:
          - step:
              type: "ShellScript"
              name: "ShellScript_1"
              identifier: "ShellScript_1"
              spec:
                shell: "Bash"
                executionTarget: {}
                source:
                  type: "Inline"
                  spec:
                    script: "echo 1"
                environmentVariables: []
                outputVariables: []
              timeout: "10m"
      tags: {}
  identifier: "rishabh2"
  name: "rishabh2"
