pipeline:
  projectIdentifier: DoNotDelete_Mayank
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  tags: {}
  stages:
    - stage:
        name: app
        identifier: app
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: test
                  identifier: test
                  template:
                    templateRef: account.NGPipeAuto_ActStepTempNZimXSPnc8
                    versionLabel: Act_Step_v2
              - step:
                  type: HarnessApproval
                  name: HarnessApproval_1
                  identifier: HarnessApproval_1
                  spec:
                    approvalMessage: Please review the following information and approve
                      the pipeline progression
                    includePipelineExecutionHistory: true
                    isAutoRejectEnabled: false
                    approvers:
                      userGroups:
                        - account._account_all_users
                      minimumCount: 1
                      disallowPipelineExecutor: false
                    approverInputs: []
                  timeout: 1d
        tags: {}
  identifier: rishapproval_Clone
  name: rish-approval - Clone
